name: Duels
main: me.realized.duels.DuelsPlugin
version: @VERSION@
softdepend: [WorldGuard, Multiverse-Core, Essentials, Factions, mcMMO, MVdWPlaceholderAPI]
# Multiverse-Core added as soft-depend due to locations being null when Duels is loaded first.
# Add any world management plugins to softdepend list if arena doesn't load properly in the generated world.

author: Realized
website: https://www.spigotmc.org/resources/duels.20171/
description: An ultimate solution to server owners wanting to create a duel system.

commands:
   duels:
     description: Administrative commands of Duels.
     aliases: [ds]
   duel:
     description: Send, accept, or deny a duel request.
     aliases: [1v1]
   spectate:
     description: Spectate a player in duel.
     aliases: [spec]
   inventoryview:
     description: View inventories after match.

permissions:
  duels.*:
    children:
      duels.admin: true

  duels.default:
    children:
      duels.duel: true
      duels.stats: true
      duels.toggle: true

  duels.admin:
    children:
      duels.default: true
      duels.spectate: true
      duels.spectate.anonymously: true