# <-> Duels v2 <->
#
#
#   Read the configuration (especially the comments above each option) carefully before PMing me on Spigot,
#   you'll probably find what you were looking for.
#
#


Patches:

  # Patch to known glitch with Essentials Vanish where you can't see the player even after unvanish.
  toggle-vanish-on-start: true

  # Patches an exploit with Essentials' /back command which allowed players to return to arena.
  set-back-location: true

  # Patches an exploit with Essentials' /tpa command which allowed players to teleport others to them.
  # Players with OP, duels.admin permission, or spectator mode will bypass the cancellation.
  cancel-teleport-to-players-in-match: true
  
  # Prevents exploit with chest access plugins or trading systems by cancelling InventoryOpen in a match.
  # Add every command and their aliases to disabled-commands is another way to patch the issue.
  fix-inventory-open: true

  # mcMMO: Prevents use of skills & abilities in a match.
  disable-mcMMO-in-match: true

  # Factions: Prevents player power loss from dying in a match.
  disable-power-loss: true

  # For v2.0 and above, teleportation with distance under 1.0 is not cancelled due to lagbacks.
  # Enable this patch to cancel any teleportation.
  strict-teleportation: false

  # If enabled, Duels will try to override any entity damage cancellation from other plugins if players are dueling.
  # For example, enabling this will allow players in same faction to duel.
  # THIS IS AN UNSAFE OPTION, DISABLE IF IT CAUSES ANY ISSUES.
  force-allow-pvp: true

  # If enabled, Duels will attempt to override any teleport cancellation from other plugins for match related teleportation.
  # THIS IS AN UNSAFE OPTION, DISABLE IF IT CAUSES ANY ISSUES.
  force-allow-teleportation: true

  # If enabled, players must stay still after sending a request.
  # Before the duel starts, Duels will check if player has moved and stop the duel if so.
  # This prevents users moving out of the selected DuelZone region after sending a request.
  # Duels will send a message after they send a duel request to someone
  # in order to notify them to stay still.
  # You may edit the sent message in messages.yml.
  cancel-match-if-moved: false





Countdown:

  # Enable countdown?
  enabled: true

  # Countdown timer's duration equals to the length of the list below. (in seconds)
  messages:
  - '&7Starting in &f5 &7seconds!'
  - '&7Starting in &f4 &7seconds!'
  - '&7Starting in &f3 &7seconds!'
  - '&7Starting in &f2 &7seconds!'
  - '&7Starting in &f1 &7second!'
  - '&7Duel starting now!'

  # While countdown is running, block launching projectiles. (Examples: Arrow, Enderpearl)
  block-projectile: true

  # While countdown is running, block pvp.
  block-pvp: true




GUI:

  # Select how many rows should each page of the GUI have.
  # Excludes the last row which contains 'previous page' & 'next page' buttons.
  # Must be in range between 1 - 5.
  kit-selector-rows: 3
  arena-selector-rows: 2

  # The display name of the map item in Arena Selector GUI.
  # display name for available arenas
  available-arena-displayname: '&9{NAME}: &aAvailable'
  # display name for in use arenas
  in-use-arena-displayname: '&9{NAME}: &cIn Use'



Spectating:

  # Players will be able to only use the following commands while in specator mode.
  whitelisted-commands:
  - 'msg'
  - 'r'
  - 'w'
  - 'pm'
  - 'reply'
  - 'tell'
  - 'whisper'
  - 'list'
  - 'stats'
  - 'dstats'
  - 'duelstats'



Dueling:

  # If enabled, match will automatically end after selected amount of seconds.
  match-max-duration:
    
    # Enable match max duration?
    enabled: true

    # The max duration for a match.
    duration: 600

  # If enabled, allows certain commands to be executed to winner and loser at the end of the match.
  match-end-commands:

    # Enable match end commands?
    enabled: false

    # Commands to be executed.
    # Available placeholder(s): {WINNER}, {LOSER}
    commands:
    - 'give {WINNER} diamond 1'
    - 'give {LOSER} dirt 1'

  # If enabled, players will have another GUI open after selecting kit that displays all arenas.
  # You can select from an arena from the list if available.
  # If someone else uses the arena while the request is pending,
  # the 'arena in use' message will display and the request will be cancelled.
  allow-arena-selecting: true

  # If enabled, players can send duel request directly without a kit or arena selection GUI popping up.
  # This will allow players to use their own inventory for dueling.
  # IMPORTANT: If you're using this option, make sure to edit the duel messages so players
  # will know they'll be using their own items!
  use-own-inventory: false

  # If enabled, players must have a cleared inventory to execute the command /duel.
  # IMPORTANT: Player inventories will be restored on duel end if this value is set to 'false'.
  requires-cleared-inventory: true

  # If enabled, players will be teleported to the latest location they were at before the start of the match after the duel.
  teleport-to-latest-location: false

  # On duel end, winner will be teleported after following amount of seconds to spawn / latest location if enabled.
  delay-until-teleport: 5

  # Allows players to drop item while in duel, if enabled.
  drop-item: false

  # Allows players to pick up item while in duel, if enabled.
  pick-up-item: true

  # All commands will be blocked while in duel, if enabled.
  # If you wish to whitelist certain commands, add them to 'whitelisted-commands' list.
  block-all-commands: false

  # Commands in the following list will be exempted from getting blocked if 'block-all-commands' is enabled.
  whitelisted-commands:
  - 'msg'
  - 'pm'
  - 'list'
  - 'w'
  - 'r'
  - 'ban'
  - 'kick'
  - 'mute'
  - 'tempban'

  # Commands in the following list will be disabled while in duel.
  # IMPORTANT: If block-all-commands is enabled, this option will not take affect.
  # If you have too many commands, 'block-all-commands' is probably a better option.
  disabled-commands:
  - 'heal'
  - 'eheal'
  - 'essentials:heal'
  - 'essentials:eheal'
  - 'kit'
  - 'ekit'
  - 'kits'
  - 'ekits'
  - 'essentials:kit'
  - 'essentials:ekit'
  - 'essentials:kits'
  - 'essentials:ekits'
  - 'enderchest'
  - 'echest'
  - 'eechest'
  - 'eenderchest'
  - 'endersee'
  - 'eendersee'
  - 'ec'
  - 'eec'
  - 'essentials:enderchest'
  - 'essentials:echest'
  - 'essentials:eechest'
  - 'essentials:eenderchest'
  - 'essentials:endersee'
  - 'essentials:eendersee'
  - 'essentials:ec'
  - 'essentials:eec'
  - 'tpaccept'
  - 'etpaccept'
  - 'tpyes'
  - 'etpyes'
  - 'essentials:tpaccept'
  - 'essentials:etpaccept'
  - 'essentials:tpyes'
  - 'essentials:etpyes'
  - 'tpahere'
  - 'etpahere'
  - 'essentials:tpahere'
  - 'essentials:etpahere'
  - 'back'
  - 'eback'
  - 'return'
  - 'ereturn'
  - 'essentials:back'
  - 'essentials:eback'
  - 'essentials:return'
  - 'essentials:ereturn'
  - 'sethome'
  - 'esethome'
  - 'createhome'
  - 'ecreatehome'
  - 'essentials:sethome'
  - 'essentials:esethome'
  - 'essentials:createhome'
  - 'essentials:ecreatehome'
  - 'spawn'
  - 'espawn'
  - 'essentials:spawn'
  - 'essentials:espawn'
  - 'vault'
  - 'chest'
  - 'pv'
  - 'playervaults'
  - 'playervaults:vault'
  - 'playervaults:chest'
  - 'playervaults:pv'
  - 'playervaults:playervaults'



# Required plugin(s): WorldGuard
DuelZone:

  # If enabled, player must be inside of the region declared below to execute the command /duel.
  enabled: false

  # The region players have to be in to use duel commands.
  region: spawn



Stats:
  # If enabled: Displays player's latest matches when /stats is executed.
  display-matches: true

  # Amount of matches to display if option above is enabled.
  amount-of-matches: 10



Soup:
  # Enable Soup?
  enabled: false

  # If enabled, arenas with name starting with the value below will have Soup Regen enabled.
  arenas-starting-with: 'soup arena'

  # Hearts to regen on soup.
  hearts-to-regen: 3.5


