name: Build and Deploy Javadoc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Write gradle.properties with JAVA_HOME
        run: echo "org.gradle.java.home=${JAVA_HOME}" >> gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

  javadoc-deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Write gradle.properties with JAVA_HOME
        run: echo "org.gradle.java.home=${JAVA_HOME}" >> gradle.properties

      - name: Generate Javadoc
        run: ./gradlew :duels-api:javadoc

      - name: Move Javadoc into subfolder
        run: |
          mkdir -p site/duels
          cp -r duels-api/build/docs/javadoc/* site/duels/

      - name: Set custom domain
        run: echo "javadocs.meteordevelopments.com" > site/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: javadocs

      - name: Send success Discord webhook
        if: success()
        run: |
          START_TIME=$(date -u -d "${{ github.event.head_commit.timestamp }}" +%s)
          END_TIME=$(date -u +%s)
          DURATION=$((END_TIME - START_TIME))
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"username\": \"GitHub\",
                 \"embeds\": [{
                   \"title\": \"<a:tick:1375852491299618997> Duels Build Succeeded\",
                   \"color\": 65280,
                   \"fields\": [
                     { \"name\": \"Author\", \"value\": \"${{ github.actor }}\", \"inline\": true },
                     { \"name\": \"Branch\", \"value\": \"${{ github.ref_name }}\", \"inline\": true },
                     { \"name\": \"Commit\", \"value\": \"[${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})\" },
                     { \"name\": \"Message\", \"value\": \"${{ github.event.head_commit.message }}\" },
                     { \"name\": \"Duration\", \"value\": \"${DURATION}s\", \"inline\": true },
                     { \"name\": \"View Run\", \"value\": \"[Open Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\", \"inline\": true }
                   ],
                   \"footer\": { \"text\": \"Javadocs at https://javadocs.meteordevelopments.com/duels\" },
                   \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\" 
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send failure Discord webhook
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"username\": \"GitHub\",
                 \"embeds\": [{
                   \"title\": \"<a:cancel:1375852920372859002> Duels Build Failed\",
                   \"color\": 16711680,
                   \"fields\": [
                     { \"name\": \"Author\", \"value\": \"${{ github.actor }}\", \"inline\": true },
                     { \"name\": \"Branch\", \"value\": \"${{ github.ref_name }}\", \"inline\": true },
                     { \"name\": \"Message\", \"value\": \"${{ github.event.head_commit.message }}\" },
                     { \"name\": \"View Run\", \"value\": \"[Open Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\", \"inline\": true }
                   ],
                   \"footer\": { \"text\": \"Check logs in GitHub Actions tab.\" },
                   \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\" 
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
